#!/bin/bash

if [[ ! -n "$DISABLE_WAYLAND" && -n "$WAYLAND_DISPLAY" ]]; then
  FLAGS="$FLAGS --enable-features=WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform-hint=auto"
    if [ -c /dev/nvidia0 ]; then
      FLAGS="$FLAGS --disable-gpu-sandbox"
    fi
fi


exec "$SNAP/usr/bin/webcord" --use-tray-icon --no-sandbox --disable-seccomp-filter-sandbox $FLAGS "$@"