name: webcord # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '4.4.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A Discord and Spacebar client implemented directly without Discord API # 79 char long summary
description: |
  A Discord and Spacebar client implemented directly without Discord API. Made in poland with the Electron framework.

license: MIT
issues: https://github.com/soumyaDghosh/webcord-snap/issues
source-code: https://github.com/SpacingBat3/WebCord
website: https://github.com/soumyaDghosh/webcord-snap
contact: soumyadeepghosh2004@zohomail.in
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
parts:
  launcher:
    source: launcher
    plugin: dump
    override-build: |
      cp launcher $CRAFT_PART_INSTALL/
  webcord:
    # See 'snapcraft plugins'
    plugin: dump
    source: https://github.com/SpacingBat3/WebCord/releases/download/v$SNAPCRAFT_PROJECT_VERSION/webcord_$SNAPCRAFT_PROJECT_VERSION_$SNAPCRAFT_TARGET_ARCH.deb
    override-build: |
      craftctl default
      rm $CRAFT_PART_INSTALL/usr/lib/webcord/chrome-sandbox
      sed -i 's|Icon=webcord|Icon=usr/share/pixmaps/webcord.png|' $CRAFT_PART_INSTALL/usr/share/applications/webcord.desktop
    stage-packages:
      - pipewire

  deps:
    plugin: nil
    stage-packages:
      - libpipewire-0.3-modules
      - libspa-0.2-modules
      - libpipewire-0.3-0
      - libappindicator3-1
      - libwebrtc-audio-processing1
      - libindicator3-7
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET/libpipewire-0.3.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libpipewire-0.3.so.0.348.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/aec/libspa-aec-null.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/aec/libspa-aec-webrtc.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/alsa/libspa-alsa.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/audioconvert/libspa-audioconvert.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/audiomixer/libspa-audiomixer.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/audiotestsrc/libspa-audiotestsrc.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/control/libspa-control.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/support/libspa-dbus.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/support/libspa-journal.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/support/libspa-support.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/test/libspa-test.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/v4l2/libspa-v4l2.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/videoconvert/libspa-videoconvert.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/videotestsrc/libspa-videotestsrc.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2/volume/libspa-volume.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-access.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-adapter.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-client-device.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-client-node.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-echo-cancel.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-fallback-sink.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-filter-chain.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-link-factory.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-loopback.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-metadata.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-portal.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-profiler.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-protocol-native.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-protocol-pulse.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-protocol-simple.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-pulse-tunnel.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-raop-discover.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-raop-sink.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-rt.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-rtkit.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-session-manager.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-spa-device-factory.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-spa-device.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-spa-node-factory.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-spa-node.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-x11-bell.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/libpipewire-module-zeroconf-discover.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3/v4l2/libpw-v4l2.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/libappindicator3.so.1
      - usr/lib/$CRAFT_ARCH_TRIPLET/libappindicator3.so.1.0.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libwebrtc_audio_processing.so.1
      - usr/lib/$CRAFT_ARCH_TRIPLET/libwebrtc_audio_processing.so.1.0.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libindicator3.so.7
      - usr/lib/$CRAFT_ARCH_TRIPLET/libindicator3.so.7.0.0


plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  webcord:
    command: launcher
    desktop: usr/share/applications/webcord.desktop
    autostart: webcord.desktop
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources
      TMPDIR: $XDG_RUNTIME_DIR
      GTK_USE_PORTAL: 1
      PIPEWIRE_CONFIG_NAME: "$SNAP/usr/share/pipewire/pipewire.conf"
      PIPEWIRE_MODULE_DIR: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3"
      SPA_PLUGIN_DIR: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2"
    extensions: [ gnome ]
    plugs:
      - password-manager-service
      - audio-playback
      - audio-record
      - camera
      - home
      - mount-observe
      - network
      - network-observe
      - opengl
      - process-control
      - removable-media
      - screen-inhibit-control
      - shmem
      - system-observe
