name: webcord
base: core22
version: '4.4.0'
summary: A Discord and Spacebar client implemented directly without Discord API
description: |
  A Discord and Spacebar client implemented directly without Discord API. Made in poland with the Electron framework.

license: MIT
issues: https://github.com/soumyaDghosh/webcord-snap/issues
source-code: https://github.com/SpacingBat3/WebCord
website: https://github.com/soumyaDghosh/webcord-snap
contact: soumyadeepghosh2004@zohomail.in
grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
parts:
  launcher:
    source: launcher
    plugin: dump
    override-build: |
      cp launcher $CRAFT_PART_INSTALL/
  webcord:
    plugin: dump
    source: https://github.com/SpacingBat3/WebCord/releases/download/v$SNAPCRAFT_PROJECT_VERSION/webcord_$SNAPCRAFT_PROJECT_VERSION_$SNAPCRAFT_TARGET_ARCH.deb
    override-build: |
      craftctl default
      rm $CRAFT_PART_INSTALL/usr/lib/webcord/chrome-sandbox
      sed -i 's|Icon=webcord|Icon=usr/share/pixmaps/webcord.png|' $CRAFT_PART_INSTALL/usr/share/applications/webcord.desktop

  deps:
    plugin: nil
    stage-packages:
      - libpipewire-0.3-modules
      - libspa-0.2-modules
      - libpipewire-0.3-0
      - libappindicator3-1
      - libwebrtc-audio-processing1
      - libindicator3-7
      - pipewire-bin


plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  webcord:
    command: launcher
    desktop: usr/share/applications/webcord.desktop
    autostart: webcord.desktop
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      GTK_USE_PORTAL: 1
      PIPEWIRE_CONFIG_NAME: "$SNAP/usr/share/pipewire/pipewire.conf"
      PIPEWIRE_MODULE_DIR: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3"
      SPA_PLUGIN_DIR: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2"
    extensions: [ gnome ]
    plugs:
      - password-manager-service
      - audio-playback
      - audio-record
      - camera
      - home
      - mount-observe
      - network
      - network-observe
      - opengl
      - process-control
      - removable-media
      - screen-inhibit-control
      - shmem
      - system-observe
