name: webcord
base: core24
title: WebCord
version: '4.11.0'
summary: A Discord and Spacebar client implemented directly without Discord API
description: |
  A Discord and Spacebar client for Text Messages and Voice & Video calls with your friends, implemented directly without Discord API. Made in poland with the Electron framework. 
  Please connect to the `password-manager-service` plug if you're facing issues. For that, run
  `sudo snap connect webcord:password-manager-service`
license: MIT
issues: https://github.com/soumyaDghosh/webcord-snap/issues
source-code: https://github.com/SpacingBat3/WebCord
website: https://github.com/soumyaDghosh/webcord-snap
contact: soumyadeepghosh2004@zohomail.in
grade: stable
confinement: strict
compression: lzo
platforms:
  amd64:
  arm64:
  armhf:

parts:
  launcher:
    source: launcher
    plugin: dump
    override-build: |
      cp launcher $CRAFT_PART_INSTALL/

  webcord:
    plugin: dump
    source: https://github.com/SpacingBat3/WebCord/releases/download/v$SNAPCRAFT_PROJECT_VERSION/webcord_$SNAPCRAFT_PROJECT_VERSION_$CRAFT_ARCH_BUILD_FOR.deb
    override-build: |
      craftctl default
      sed -i 's|Icon=webcord|Icon=usr/share/pixmaps/webcord.png|' $CRAFT_PART_INSTALL/usr/share/applications/webcord.desktop
    prime:
      - -usr/lib/webcord/chrome-sandbox

  # Needed for setting the proper desktop file name in the electron apps
  patch-desktop-file-name:
    after: [webcord]
    source: https://github.com/snapcrafters/patch-desktop-file-name.git
    source-subdir: electron
    plugin: nil
    override-build: |
      pip install asarPy --break-system-packages
      python3 $CRAFT_PART_SRC_WORK/patch-desktop-filename.py $CRAFT_STAGE/usr/lib/webcord/resources/app.asar

plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  webcord:
    command: launcher
    desktop: usr/share/applications/webcord.desktop
    autostart: webcord.desktop
    common-id: io.github.spacingbat3.webcord
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    extensions: [ gnome ]
    plugs:
      - home
      - removable-media
      - password-manager-service
      - audio-playback
      - audio-record
      - camera
      - network
      - opengl
      - shmem
      - unity7
