name: webcord # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '4.3.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A Discord and Spacebar client implemented directly without Discord API # 79 char long summary
description: |
  A Discord and Spacebar client implemented directly without Discord API. Made in poland with the Electron framework.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  webcord:
    # See 'snapcraft plugins'
    plugin: dump
    source: https://github.com/SpacingBat3/WebCord/releases/download/v$SNAPCRAFT_PROJECT_VERSION/webcord_$SNAPCRAFT_PROJECT_VERSION_$SNAPCRAFT_TARGET_ARCH.deb
    override-prime: |
      craftctl default
      rm $CRAFT_PART_INSTALL/usr/lib/webcord/chrome-sandbox
      sed -i 's|Icon=webcord|Icon=${SNAP}/usr/share/pixmaps/webcord.png|' ${CRAFT_PART_INSTALL}/usr/share/applications/webcord.desktop


plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  webcord:
    command: usr/bin/webcord --no-sandbox --disable-seccomp-filter-sandbox --use-try-icon
    desktop: usr/share/applications/webcord.desktop
    autostart: webcord.desktop
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources
      TMPDIR: $XDG_RUNTIME_DIR
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
      GTK_USE_PORTAL: 1
    extensions: [ gnome ]
    plugs:
      - audio-playback
      - audio-record
      - camera
      - home
      - mount-observe
      - network
      - network-observe
      - opengl
      - process-control
      - removable-media
      - screen-inhibit-control
      - shmem
      - system-observe
