name: Update Snapcraft.yaml

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: write-all

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch new version number
        id: fetch-version
        run: |
          # Use wget or curl to fetch the new version number from an external source
          # For example, assuming the version is available in a text file at a URL
          curl -s https://raw.githubusercontent.com/SpacingBat3/WebCord/master/package.json > package.json
          new_version=$(jq -r '.version' package.json)
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare-versions
        run: |
          git config user.email "soumyadeepghosh2004@zohomail.in"
          git config user.name "soumyaDghosh"
          current_version=$(grep 'version:' snap/snapcraft.yaml | awk -F"'" '{print $2}')
          new_version=${{ steps.fetch-version.outputs.new_version }}
          if [[ "$current_version" != "$new_version" ]]; then
            echo "Updating Snapcraft.yaml..."
            sed -i "s/version: '$current_version'/version: '$new_version'/" snap/snapcraft.yaml
            echo "Staging the changes"
            git add snap/snapcraft.yaml
            git commit -m "Update Snapcraft.yaml to version $new_version"
            git push
          else
            echo "Versions match. No update needed."
          fi
      - name: Cleanup
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
